### ISSUE TITLE
Sky View not working

### ISSUE THREAD

**Issue by pouryaali** [AntonelloDN/SkyViewAnalysis#1]
Hello, I just installed Sky View on my Sketchup, but it doesn't work for me, seems it's not activated in my Sketchup... the only thing I can see is that orange/red dot at the beginning, not other options! Cant apply the dom!
There is no dom that I can work on it.

**Comment by AntonelloDN** [comment]
Hi @pouryaali, can you provide:
1. Your Sketchup version
2. A screenshot. It is important to see the status bar where you should type `radius@accuracy` e.g. `20@34`

**Comment by pouryaali** [comment]
Thank you , it works now , actually I didn't consider radius amount before.

**Comment by AntonelloDN** [comment]
Ok, good! I close this issue.
